baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog naveen srinivasan"
  keywords = "homepage, blog, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
# Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/snaveen"

  [[params.social]]
    name = "github"
    url  = "https://github.com/naveensrinivasan"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/naveensrinivasan/"
[languages]
  [languages.en]
    title = "naveen srinivasan"
    subtitle = "Write code.Loves to read"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "posts"
        url = "/posts"
